// !!! DO NOT ADD #pragma once !!! //

// Twitch "ultraviolent" purple hex codes.
//RGB_MATRIX_EFFECT(twitch_purple)

//#ifdef RGB_MATRIX_CUSTOM_EFFECT_IMPLS

//static bool twitch_purple(effect_params_t* params) {
//  RGB_MATRIX_USE_LIMITS(led_min, led_max);
//  for (uint8_t i = led_min; i < led_max; i++) {
//    rgb_matrix_set_color(i, 0x87, 0x4a, 0xf6);
//  }
//  return led_max < DRIVER_LED_TOTAL;
//}

//#endif
